In [1]:
from get_data_bat import batStats_clean20

batStats_clean20.head()

,IDfg,Season,Name,Team,Age,IBB,SO,SB,BU,BABIP,...,CB%,O-Contact%,wGDP,Oppo%,OBP+,SLG+,Pull%+,Soft%+,Hard%+,L-WAR
3952,1,2006,Alfredo Amezaga,FLA,0.346154,0.033333,0.176744,0.256410,0.191011,0.474104,...,0.125000,0.693642,0.601852,0.450402,0.349206,0.179856,0.362069,0.662921,0.210884,0.279503
2614,1,2007,Alfredo Amezaga,FLA,0.384615,0.000000,0.204651,0.166667,0.202247,0.470120,...,0.161765,0.725434,0.638889,0.455764,0.333333,0.230216,0.413793,0.471910,0.292517,0.335404
1034,2,2002,Garret Anderson,ANA,0.423077,0.091667,0.334884,0.076923,0.011236,0.529880,...,0.669118,0.417630,0.796296,0.286863,0.373016,0.553957,0.637931,0.224719,0.659864,0.440994
431,2,2003,Garret Anderson,ANA,0.461538,0.083333,0.348837,0.076923,0.000000,0.597610,...,0.625000,0.514451,0.601852,0.297587,0.396825,0.546763,0.586207,0.365169,0.523810,0.527950
4361,2,2004,Garret Anderson,ANA,0.500000,0.050000,0.311628,0.025641,0.000000,0.633466,...,0.492647,0.410405,0.694444,0.233244,0.380952,0.381295,0.603448,0.297753,0.448980,0.260870